// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzIF2Av5gAqXaFD370V7CruhP7QKGO0TQ',
    appId: '1:37754135220:web:aa19f473d786c636672de1',
    messagingSenderId: '37754135220',
    projectId: 'mentormatch-467',
    authDomain: 'mentormatch-467.firebaseapp.com',
    storageBucket: 'mentormatch-467.appspot.com',
    measurementId: 'G-C7XLDTK27M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwkUd4kbuLSDO3_q1bt3bkiuxj4Csqf8Q',
    appId: '1:37754135220:android:2a938fd75f7337b0672de1',
    messagingSenderId: '37754135220',
    projectId: 'mentormatch-467',
    storageBucket: 'mentormatch-467.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRnWZyHXrbVxTS2yUkhRn_5tVFyy3taMU',
    appId: '1:37754135220:ios:76752b9e07b6a769672de1',
    messagingSenderId: '37754135220',
    projectId: 'mentormatch-467',
    storageBucket: 'mentormatch-467.appspot.com',
    iosBundleId: 'com.example.mentorMatch',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRnWZyHXrbVxTS2yUkhRn_5tVFyy3taMU',
    appId: '1:37754135220:ios:76752b9e07b6a769672de1',
    messagingSenderId: '37754135220',
    projectId: 'mentormatch-467',
    storageBucket: 'mentormatch-467.appspot.com',
    iosBundleId: 'com.example.mentorMatch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzIF2Av5gAqXaFD370V7CruhP7QKGO0TQ',
    appId: '1:37754135220:web:fb841186d605e94f672de1',
    messagingSenderId: '37754135220',
    projectId: 'mentormatch-467',
    authDomain: 'mentormatch-467.firebaseapp.com',
    storageBucket: 'mentormatch-467.appspot.com',
    measurementId: 'G-7Y28EP1PHS',
  );

}